[jjiles.interface]
# Which fzf style to use (minimal, default or full):
fzf-style = "default"
# Where to place the header (showing the breadcrumbs) and the search bar:
menu-position = "top"
# Whether the search bar is visible by default or not:
search-bar-visible = true

# How to draw borders around the elements of the interface.
# See `man fzf` for more info:
[jjiles.interface.borders]
header = "rounded"
input = "none"
list = "none"
preview = "line"

[jjiles.diff]
# Ask delta to generate a double-column diff if we have more than a
# certain amount of characters per line. Set it to a very high value
# to always use single-column diffs
double-column-threshold = 130

# Colors used later can be a key in the 'theme-mappings' section below.
# In such case, the color will depend on system theme. This is for users
# who want their configuration to look OK whatever the system theme
[jjiles.colors.theme-mappings]
opaque.dark = "black" # if system theme is "dark", "opaque" will be replaced by "black"
opaque.light = "white"
# If system theme cannot be detected, everything using "opaque" will be ignored

high-contrast.dark = "#ffffff"
high-contrast.light = "#000000"
high-contrast.default = "#888888" # here we provide a default if system theme cannot be detected

# Will be passed to fzf --color. See `man fzf` for more info.
[jjiles.colors.fzf]
header-bg = "opaque"
list-border = "cyan"
pointer = "high-contrast"
preview-bg = "opaque"
preview-border = "high-contrast"

# Will be passed straight to fzf --bind. See `man fzf` for more info:
[jjiles.bindings.fzf]
# Empty search bar, or (if already empty) quit without printing anything:
"esc" = "cancel"
# Quit and print the currently selected commit/operation:
"ctrl-q,ctrl-g" = "accept"
# Scroll log list with mouse wheel (repeated to scroll faster):
scroll-up = "offset-up+offset-up+offset-up"
scroll-down = "offset-down+offset-down+offset-down"
# Scroll preview panel with mouse wheel (repeated to scroll faster):
preview-scroll-up = "preview-up+preview-up+preview-up"
preview-scroll-down = "preview-down+preview-down+preview-down"
# Page up/down in log list:
"alt-down,alt-j" = "page-down"
"alt-up,alt-k" = "page-up"
# Page up/down in preview panel:
page-down = "preview-page-down"
page-up = "preview-page-up"
ctrl-d = "preview-half-page-down"
ctrl-u = "preview-half-page-up"
